// repo/scripts/generate-api-client.ts -- orchestrator for full client regeneration
// Run from repo root: pnpm generate:api-client [--commit] [--push]

import { execSync, spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

const REPO_ROOT = process.cwd();
const PACKAGE_DIR = join(REPO_ROOT, 'packages', 'api-client');

function log(level: 'info' | 'ok' | 'fail', msg: string): void {
  console.log(`[orchestrator:${level}] ${msg}`);
}

function isBackendRunning(): boolean {
  try {
    execSync('curl -sf http://localhost:4000/health', { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

async function startBackendIfNeeded(): Promise<{ stop: () => void } | null> {
  if (isBackendRunning()) {
    log('info', 'backend already up');
    return null;
  }
  log('info', 'starting backend in background');
  const child = spawn('pnpm', ['--filter', '@insurtech/api', 'dev'], {
    cwd: REPO_ROOT,
    detached: true,
    stdio: 'ignore',
  });
  child.unref();

  // Wait up to 60s
  for (let i = 0; i < 60; i++) {
    await new Promise((r) => setTimeout(r, 1000));
    if (isBackendRunning()) {
      log('ok', `backend up after ${i + 1}s`);
      return { stop: () => process.kill(-(child.pid ?? 0)) };
    }
  }
  throw new Error('Backend failed to start within 60s');
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const shouldCommit = args.includes('--commit');
  const shouldPush = args.includes('--push');

  if (!existsSync(PACKAGE_DIR)) {
    throw new Error(`Package not found: ${PACKAGE_DIR}`);
  }

  const handle = await startBackendIfNeeded();
  try {
    log('info', 'running pnpm generate inside packages/api-client');
    execSync('pnpm generate', { cwd: PACKAGE_DIR, stdio: 'inherit' });
    execSync('pnpm validate', { cwd: PACKAGE_DIR, stdio: 'inherit' });
    log('ok', 'generation + validation complete');
  } finally {
    handle?.stop();
  }

  if (shouldCommit) {
    execSync('git add packages/api-client/src/types.gen.ts', {
      cwd: REPO_ROOT,
      stdio: 'inherit',
    });
    execSync(
      `git commit -m "chore(api-client): regenerate types from OpenAPI" -m "Auto-generated by scripts/generate-api-client.ts"`,
      { cwd: REPO_ROOT, stdio: 'inherit' },
    );
    log('ok', 'committed');
    if (shouldPush) {
      execSync('git push', { cwd: REPO_ROOT, stdio: 'inherit' });
      log('ok', 'pushed');
    }
  }
}

void main().catch((err: unknown) => {
  log('fail', (err as Error).message);
  process.exit(1);
});
