/**
 * CalendarProvider -- Sprint 8 Tache 8.10b.
 *
 * Common interface implemented by GoogleCalendarProvider and
 * OutlookCalendarProvider. The OAuth orchestrator service is agnostic
 * to provider specifics ; differences (channel vs subscription model,
 * header validation, scope strings) are isolated in each implementation.
 *
 * Reference : B-08 Tache 3.2.5.
 */

import type { CalendarProviderName } from '../config/oauth-calendar.config.js';

/** OAuth token exchange response (normalized across providers). */
export interface TokenResponse {
  readonly accessToken: string;
  readonly refreshToken?: string;
  readonly expiresAt: Date;
  readonly scope?: string;
  /** Provider-specific token type (typically "Bearer"). */
  readonly tokenType?: string;
}

/** Webhook subscription record (normalized). */
export interface WebhookSubscription {
  /** Provider's subscription / channel id. */
  readonly id: string;
  /** Google : resource id. Microsoft : not applicable. */
  readonly resourceId?: string;
  /** Subscription expiry (Google 7d max, MS Graph ~70h max). */
  readonly expiresAt: Date;
  /**
   * Validation token / client state echoed back during push notifications.
   * Persisted to verify webhook authenticity (anti-replay, anti-spoofing).
   */
  readonly clientState?: string;
}

/**
 * External calendar event input (normalized DTO sent to providers).
 * Phase 2 (Task 8.12) -- bi-directional sync push.
 */
export interface ExternalCalendarEventInput {
  readonly title: string;
  readonly description?: string;
  readonly startAt: Date;
  readonly endAt: Date;
  readonly timezone: string;
  readonly attendees: ReadonlyArray<{ name: string; email?: string }>;
  /** Free-form location ; we typically build "Room (City)". */
  readonly location?: string;
}

/** External calendar event response (returned by createEvent / getEvent). */
export interface ExternalCalendarEvent extends ExternalCalendarEventInput {
  readonly id: string;
  readonly lastModifiedAt: Date;
  readonly createdAt: Date;
}

/**
 * Parsed webhook notification (provider-agnostic). Phase 2 -- consumed by
 * CalendarSyncWorkerService.handleExternalChange.
 */
export interface WebhookNotificationParsed {
  /** Provider's subscription / channel id. */
  readonly subscriptionId: string;
  /** External event id whose change triggered the notification. */
  readonly resourceId: string;
  /** Mutation type. */
  readonly changeType: 'created' | 'updated' | 'deleted';
  /**
   * Microsoft only : lifecycle notifications (subscription about to expire /
   * removed / reauth needed). Google has no equivalent ; only `null` for it.
   */
  readonly lifecycleEvent?:
    | 'subscriptionRenew'
    | 'subscriptionRemove'
    | 'reauthorizationRequired';
}

/** Webhook validation result (from incoming HTTP request). */
export interface WebhookValidation {
  readonly valid: boolean;
  /** Provider's subscription/channel id, extracted from headers. */
  readonly subscriptionId?: string;
  /** Resource id of the changed object (event), if extractable. */
  readonly resourceId?: string;
  /** Reason for invalidity (for logging). */
  readonly reason?: string;
  /**
   * Microsoft only : during initial subscription handshake, MS Graph sends a
   * GET with `validationToken` query param ; provider returns the echo value
   * here and controller responds with text/plain. Empty string for normal
   * notifications.
   */
  readonly validationTokenEcho?: string;
}

export interface CalendarProvider {
  readonly name: CalendarProviderName;

  /**
   * Builds the OAuth2 authorization URL the user is redirected to. `state`
   * is the CSRF token persisted in Redis ; `redirectUri` must match the
   * URI registered in the provider's developer console.
   */
  getAuthorizationUrl(state: string, redirectUri: string): string;

  /** Exchanges the authorization code received at the callback for tokens. */
  exchangeCodeForTokens(code: string, redirectUri: string): Promise<TokenResponse>;

  /**
   * Refreshes an expired access token using the refresh token. Returns the
   * new access token + potentially-rotated refresh token + new expiry.
   */
  refreshAccessToken(refreshToken: string): Promise<TokenResponse>;

  /**
   * Fetches the authenticated user's email address (used to associate the
   * token row with `provider_account_id`).
   */
  getUserEmail(accessToken: string): Promise<string>;

  /**
   * Creates a webhook subscription so the provider pushes notifications to
   * our `webhookUrl` when calendar events change.
   *
   * @param clientState arbitrary string echoed back in notifications. Used
   *   to validate webhook authenticity. Generated by orchestrator + stored
   *   in CalendarSync row + checked on each incoming notification.
   */
  createWebhookSubscription(
    accessToken: string,
    webhookUrl: string,
    clientState: string,
  ): Promise<WebhookSubscription>;

  /**
   * Renews an existing webhook subscription (extends `expiresAt`). Called by
   * CalendarWebhookManagerService cron before expiry.
   */
  renewWebhookSubscription(
    accessToken: string,
    subscriptionId: string,
  ): Promise<WebhookSubscription>;

  /** Deletes a webhook subscription (called on disconnect). */
  deleteWebhookSubscription(
    accessToken: string,
    subscriptionId: string,
  ): Promise<void>;

  /**
   * Validates an incoming webhook HTTP request. Implementations check
   * provider-specific headers (X-Goog-Channel-Token for Google,
   * clientState for Microsoft) against the value stored in the
   * CalendarSync row.
   *
   * @param expectedClientState the value stored at subscription creation.
   *   Implementations look it up in the row matched by `subscriptionId`.
   */
  validateWebhookPayload(
    headers: Record<string, string | string[] | undefined>,
    rawBody: string | undefined,
    query: Record<string, string | undefined>,
    expectedClientState: string | undefined,
  ): WebhookValidation;

  // ==========================================================================
  // Phase 2 (Task 8.12) -- Event CRUD + parsed webhook
  // ==========================================================================

  /** Creates a new event in the user's primary calendar. */
  createEvent(
    accessToken: string,
    event: ExternalCalendarEventInput,
  ): Promise<ExternalCalendarEvent>;

  /** Updates an existing event (full replace -- attendees, time, title). */
  updateEvent(
    accessToken: string,
    eventId: string,
    event: ExternalCalendarEventInput,
  ): Promise<ExternalCalendarEvent>;

  /** Deletes an event by id. Idempotent ; missing event is not an error. */
  deleteEvent(accessToken: string, eventId: string): Promise<void>;

  /** Fetches an event by id. Returns null when not found (404). */
  getEvent(accessToken: string, eventId: string): Promise<ExternalCalendarEvent | null>;

  /**
   * Extracts a normalized notification from an inbound webhook request.
   * Returns null for unparseable / lifecycle-only / handshake payloads --
   * caller treats null as "ack but skip processing".
   *
   * Validation (clientState / X-Goog-Channel-Token) is performed by
   * validateWebhookPayload BEFORE this is called.
   */
  parseWebhookNotification(
    headers: Record<string, string | string[] | undefined>,
    body: unknown,
  ): WebhookNotificationParsed | null;
}
