/**
 * CalendarProvider -- Sprint 8 Tache 8.10b.
 *
 * Common interface implemented by GoogleCalendarProvider and
 * OutlookCalendarProvider. The OAuth orchestrator service is agnostic
 * to provider specifics ; differences (channel vs subscription model,
 * header validation, scope strings) are isolated in each implementation.
 *
 * Reference : B-08 Tache 3.2.5.
 */

import type { CalendarProviderName } from '../config/oauth-calendar.config.js';

/** OAuth token exchange response (normalized across providers). */
export interface TokenResponse {
  readonly accessToken: string;
  readonly refreshToken?: string;
  readonly expiresAt: Date;
  readonly scope?: string;
  /** Provider-specific token type (typically "Bearer"). */
  readonly tokenType?: string;
}

/** Webhook subscription record (normalized). */
export interface WebhookSubscription {
  /** Provider's subscription / channel id. */
  readonly id: string;
  /** Google : resource id. Microsoft : not applicable. */
  readonly resourceId?: string;
  /** Subscription expiry (Google 7d max, MS Graph ~70h max). */
  readonly expiresAt: Date;
  /**
   * Validation token / client state echoed back during push notifications.
   * Persisted to verify webhook authenticity (anti-replay, anti-spoofing).
   */
  readonly clientState?: string;
}

/** Webhook validation result (from incoming HTTP request). */
export interface WebhookValidation {
  readonly valid: boolean;
  /** Provider's subscription/channel id, extracted from headers. */
  readonly subscriptionId?: string;
  /** Resource id of the changed object (event), if extractable. */
  readonly resourceId?: string;
  /** Reason for invalidity (for logging). */
  readonly reason?: string;
  /**
   * Microsoft only : during initial subscription handshake, MS Graph sends a
   * GET with `validationToken` query param ; provider returns the echo value
   * here and controller responds with text/plain. Empty string for normal
   * notifications.
   */
  readonly validationTokenEcho?: string;
}

export interface CalendarProvider {
  readonly name: CalendarProviderName;

  /**
   * Builds the OAuth2 authorization URL the user is redirected to. `state`
   * is the CSRF token persisted in Redis ; `redirectUri` must match the
   * URI registered in the provider's developer console.
   */
  getAuthorizationUrl(state: string, redirectUri: string): string;

  /** Exchanges the authorization code received at the callback for tokens. */
  exchangeCodeForTokens(code: string, redirectUri: string): Promise<TokenResponse>;

  /**
   * Refreshes an expired access token using the refresh token. Returns the
   * new access token + potentially-rotated refresh token + new expiry.
   */
  refreshAccessToken(refreshToken: string): Promise<TokenResponse>;

  /**
   * Fetches the authenticated user's email address (used to associate the
   * token row with `provider_account_id`).
   */
  getUserEmail(accessToken: string): Promise<string>;

  /**
   * Creates a webhook subscription so the provider pushes notifications to
   * our `webhookUrl` when calendar events change.
   *
   * @param clientState arbitrary string echoed back in notifications. Used
   *   to validate webhook authenticity. Generated by orchestrator + stored
   *   in CalendarSync row + checked on each incoming notification.
   */
  createWebhookSubscription(
    accessToken: string,
    webhookUrl: string,
    clientState: string,
  ): Promise<WebhookSubscription>;

  /**
   * Renews an existing webhook subscription (extends `expiresAt`). Called by
   * CalendarWebhookManagerService cron before expiry.
   */
  renewWebhookSubscription(
    accessToken: string,
    subscriptionId: string,
  ): Promise<WebhookSubscription>;

  /** Deletes a webhook subscription (called on disconnect). */
  deleteWebhookSubscription(
    accessToken: string,
    subscriptionId: string,
  ): Promise<void>;

  /**
   * Validates an incoming webhook HTTP request. Implementations check
   * provider-specific headers (X-Goog-Channel-Token for Google,
   * clientState for Microsoft) against the value stored in the
   * CalendarSync row.
   *
   * @param expectedClientState the value stored at subscription creation.
   *   Implementations look it up in the row matched by `subscriptionId`.
   */
  validateWebhookPayload(
    headers: Record<string, string | string[] | undefined>,
    rawBody: string | undefined,
    query: Record<string, string | undefined>,
    expectedClientState: string | undefined,
  ): WebhookValidation;
}
