// @insurtech/api-client -- generation script
// Steps:
//   1. probe backend /health (timeout 30s, retry 1s)
//   2. fetch OpenAPI JSON from /docs-json
//   3. validate OpenAPI structure
//   4. run openapi-typescript -> TS source string
//   5. post-process: prepend header, run prettier
//   6. atomic write to src/types.gen.ts
//   7. typecheck verification
//   8. report stats

import { rename, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';
import openapiTS, { astToString } from 'openapi-typescript';
import prettier from 'prettier';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = join(__dirname, '..');
const TARGET = join(PACKAGE_ROOT, 'src', 'types.gen.ts');
const TARGET_TMP = TARGET + '.tmp';

const API_BASE = process.env['NEXT_PUBLIC_API_URL'] ?? 'http://localhost:4000';
const HEALTH_URL = `${API_BASE}/health`;
const DOCS_URL = `${API_BASE}/docs-json`;
const TIMEOUT_MS = Number(process.env['API_GENERATE_TIMEOUT_MS'] ?? 30_000);
const RETRY_DELAY_MS = Number(process.env['API_GENERATE_RETRY_DELAY_MS'] ?? 1_000);

function log(level: 'info' | 'ok' | 'warn' | 'fail', msg: string): void {
  const prefix = { info: '[generate]', ok: '[ok]', warn: '[warn]', fail: '[fail]' }[level];
  console.log(`${prefix} ${msg}`);
}

async function probeBackend(): Promise<void> {
  const start = Date.now();
  log('info', `probing backend at ${HEALTH_URL}`);
  while (Date.now() - start < TIMEOUT_MS) {
    try {
      const res = await fetch(HEALTH_URL, { signal: AbortSignal.timeout(2000) });
      if (res.ok) {
        log('ok', `backend ready (${Date.now() - start}ms)`);
        return;
      }
    } catch {
      // not ready, retry
    }
    await new Promise((r) => setTimeout(r, RETRY_DELAY_MS));
  }
  throw new Error(
    `Backend not reachable on ${HEALTH_URL} after ${TIMEOUT_MS}ms.\n` +
      `Start it with: pnpm --filter @insurtech/api dev`,
  );
}

async function fetchOpenApiJson(): Promise<unknown> {
  log('info', `fetching OpenAPI JSON from ${DOCS_URL}`);
  const res = await fetch(DOCS_URL, {
    headers: { 'Cache-Control': 'no-cache' },
  });
  if (!res.ok) {
    throw new Error(`Failed to fetch OpenAPI: ${res.status} ${res.statusText}`);
  }
  const json = await res.json();
  log('ok', 'OpenAPI JSON fetched');
  return json;
}

function validateOpenApi(spec: unknown): void {
  if (!spec || typeof spec !== 'object') throw new Error('OpenAPI spec is not an object');
  const s = spec as Record<string, unknown>;
  if (!s['openapi'] || !(s['openapi'] as string).startsWith('3.')) {
    throw new Error(`Unsupported OpenAPI version: ${String(s['openapi'])}`);
  }
  if (!s['paths']) {
    log('warn', 'OpenAPI spec has no paths -- backend probably empty (Sprint 3 minimal)');
  }
}

async function generateTypes(spec: unknown): Promise<string> {
  log('info', 'generating TypeScript types via openapi-typescript');
  const ast = await openapiTS(spec as Parameters<typeof openapiTS>[0], {
    additionalProperties: false,
    alphabetize: true,
    arrayLength: false,
    defaultNonNullable: true,
    emptyObjectsUnknown: true,
    enum: true,
    immutable: false,
  });
  return astToString(ast);
}

async function postProcess(rawTs: string, spec: unknown): Promise<string> {
  const s = spec as Record<string, unknown>;
  const info = s['info'] as Record<string, unknown> | undefined;
  const header = `/**
 * AUTO-GENERATED FILE -- DO NOT EDIT MANUALLY
 *
 * Generated by openapi-typescript 7.4.4 from OpenAPI spec.
 * Source: ${DOCS_URL}
 * OpenAPI version: ${String(s['openapi'])}
 * API title: ${String(info?.['title'] ?? 'unknown')}
 * API version: ${String(info?.['version'] ?? 'unknown')}
 * Generated at: ${new Date().toISOString()}
 *
 * To regenerate: pnpm generate:api-client
 *
 * Linter rule no-edit-generated-types is enforced in CI.
 */

`;

  const config = (await prettier.resolveConfig(PACKAGE_ROOT)) ?? {};
  const formatted = await prettier.format(header + rawTs, {
    ...config,
    parser: 'typescript',
  });
  return formatted;
}

async function atomicWrite(content: string): Promise<void> {
  await writeFile(TARGET_TMP, content, 'utf8');
  await rename(TARGET_TMP, TARGET);
  log('ok', `written ${TARGET}`);
}

function runTypecheck(): void {
  log('info', 'running TypeScript typecheck on generated file');
  try {
    execSync('pnpm typecheck', { cwd: PACKAGE_ROOT, stdio: 'inherit' });
    log('ok', 'typecheck passed');
  } catch {
    throw new Error('Typecheck failed on generated types.gen.ts -- regeneration is broken');
  }
}

function reportStats(spec: unknown, generatedTs: string): void {
  const s = spec as Record<string, unknown>;
  const pathsObj = s['paths'] as Record<string, unknown> | undefined;
  const components = s['components'] as Record<string, unknown> | undefined;
  const schemas = components?.['schemas'] as Record<string, unknown> | undefined;

  const pathCount = Object.keys(pathsObj ?? {}).length;
  const operationCount = Object.values(pathsObj ?? {}).reduce((sum: number, item: unknown) => {
    if (!item || typeof item !== 'object') return sum;
    const methods = ['get', 'post', 'put', 'patch', 'delete'];
    return sum + methods.filter((k) => k in (item as Record<string, unknown>)).length;
  }, 0);
  const schemaCount = Object.keys(schemas ?? {}).length;
  const lines = generatedTs.split('\n').length;
  log(
    'ok',
    `stats: ${pathCount} paths | ${operationCount} operations | ${schemaCount} schemas | ${lines} lines generated`,
  );
}

async function main(): Promise<void> {
  try {
    await probeBackend();
    const spec = await fetchOpenApiJson();
    validateOpenApi(spec);
    const rawTs = await generateTypes(spec);
    const finalTs = await postProcess(rawTs, spec);
    await atomicWrite(finalTs);
    runTypecheck();
    reportStats(spec, finalTs);
    log('ok', 'generation complete');
  } catch (err) {
    log('fail', (err as Error).message);
    process.exit(1);
  }
}

void main();
