/**
 * AUTO-GENERATED FILE -- DO NOT EDIT MANUALLY
 *
 * This file is generated by `pnpm generate:api-client` from the OpenAPI Swagger
 * exposed by the NestJS API at http://localhost:4000/docs-json.
 *
 * To regenerate:
 *   1. Start backend: `pnpm --filter @insurtech/api dev`
 *   2. Run: `pnpm generate:api-client`
 *
 * Sprint 4 placeholder content: only minimal endpoints from Sprint 3 backend.
 * Sprint 5+ will progressively enrich this file as backend exposes more endpoints.
 *
 * Linter rule: `no-edit-generated-types` enforced in CI (.eslintrc).
 *
 * Last regenerated: <PENDING -- replaced at first run of generate.ts>
 * Source OpenAPI version: <PENDING>
 * Source NestJS commit: <PENDING>
 */

export interface paths {
  '/health': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': {
              status: 'ok';
              timestamp: string;
              version: string;
              uptime: number;
            };
          };
        };
      };
    };
  };
  '/version': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': {
              version: string;
              commit: string;
              env: 'development' | 'staging' | 'production';
            };
          };
        };
      };
    };
  };
}

export type components = Record<string, never>;
export type operations = Record<string, never>;
export type webhooks = Record<string, never>;
