/**
 * Skalean InsurTech v2.2 -- Env schema Zod runtime validation
 *
 * Reference :
 *   - 00-pilotage/meta-prompts/B-01-sprint-01-bootstrap.md (Tache 1.1.8)
 *   - 8-skalean-insurtech-prompt-master.md Section 3 (Zod strict)
 *   - decision-006 (no-emoji)
 *   - 2-variables-environnement.env catalog
 */
import { z } from 'zod';
export declare const EnvSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "staging", "production"]>>;
    APP_VERSION: z.ZodDefault<z.ZodString>;
    API_PORT: z.ZodDefault<z.ZodNumber>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["fatal", "error", "warn", "info", "debug", "trace"]>>;
    TZ: z.ZodDefault<z.ZodString>;
    DATABASE_URL: z.ZodString;
    DATABASE_POOL_MIN: z.ZodDefault<z.ZodNumber>;
    DATABASE_POOL_MAX: z.ZodDefault<z.ZodNumber>;
    DATABASE_LOG: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    REDIS_URL: z.ZodString;
    KAFKA_BROKERS: z.ZodEffects<z.ZodArray<z.ZodString, "many">, string[], unknown>;
    KAFKA_CLIENT_ID: z.ZodDefault<z.ZodString>;
    KAFKA_GROUP_ID: z.ZodDefault<z.ZodString>;
    S3_ENDPOINT: z.ZodOptional<z.ZodString>;
    S3_REGION: z.ZodDefault<z.ZodString>;
    S3_ACCESS_KEY_ID: z.ZodString;
    S3_SECRET_ACCESS_KEY: z.ZodString;
    S3_FORCE_PATH_STYLE: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    S3_KMS_KEY_BASE: z.ZodOptional<z.ZodString>;
    JWT_SECRET: z.ZodString;
    JWT_REFRESH_SECRET: z.ZodString;
    MFA_SECRET_ENCRYPTION_KEY: z.ZodString;
    PASSWORD_PEPPER: z.ZodString;
    JWT_ACCESS_TTL: z.ZodDefault<z.ZodString>;
    JWT_REFRESH_TTL: z.ZodDefault<z.ZodString>;
    ARGON2_MEMORY_COST: z.ZodDefault<z.ZodNumber>;
    ARGON2_TIME_COST: z.ZodDefault<z.ZodNumber>;
    ARGON2_PARALLELISM: z.ZodDefault<z.ZodNumber>;
    EMAIL_SMTP_HOST: z.ZodDefault<z.ZodString>;
    EMAIL_SMTP_PORT: z.ZodDefault<z.ZodNumber>;
    EMAIL_SMTP_USER: z.ZodOptional<z.ZodString>;
    EMAIL_SMTP_PASSWORD: z.ZodOptional<z.ZodString>;
    EMAIL_FROM_ADDRESS: z.ZodDefault<z.ZodString>;
    EMAIL_FROM_NAME: z.ZodDefault<z.ZodString>;
    WHATSAPP_API_URL: z.ZodOptional<z.ZodString>;
    WHATSAPP_PHONE_NUMBER_ID: z.ZodOptional<z.ZodString>;
    WHATSAPP_ACCESS_TOKEN: z.ZodOptional<z.ZodString>;
    SKALEAN_AI_BASE_URL: z.ZodDefault<z.ZodString>;
    SKALEAN_AI_API_KEY: z.ZodDefault<z.ZodString>;
    SKALEAN_AI_USE_MOCK: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    SENTRY_DSN: z.ZodOptional<z.ZodString>;
    OTEL_EXPORTER_OTLP_ENDPOINT: z.ZodOptional<z.ZodString>;
    OTEL_DEBUG: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    OTEL_SERVICE_NAME: z.ZodDefault<z.ZodString>;
    CORS_ORIGINS: z.ZodDefault<z.ZodEffects<z.ZodArray<z.ZodString, "many">, string[], unknown>>;
    NEXT_PUBLIC_API_URL: z.ZodDefault<z.ZodString>;
    NEXT_PUBLIC_MAPBOX_TOKEN: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SENTRY_DSN: z.ZodOptional<z.ZodString>;
    MCP_SERVER_URL: z.ZodDefault<z.ZodString>;
    CMI_API_URL: z.ZodOptional<z.ZodString>;
    CMI_API_KEY: z.ZodOptional<z.ZodString>;
    YOUCAN_API_URL: z.ZodOptional<z.ZodString>;
    YOUCAN_API_KEY: z.ZodOptional<z.ZodString>;
    BARID_ESIGN_API_URL: z.ZodOptional<z.ZodString>;
    BARID_ESIGN_API_KEY: z.ZodOptional<z.ZodString>;
    ATLAS_VAULT_URL: z.ZodOptional<z.ZodString>;
    ATLAS_VAULT_TOKEN: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    APP_VERSION: string;
    NODE_ENV: "development" | "test" | "staging" | "production";
    LOG_LEVEL: "info" | "fatal" | "error" | "warn" | "debug" | "trace";
    REDIS_URL: string;
    KAFKA_BROKERS: string[];
    KAFKA_CLIENT_ID: string;
    API_PORT: number;
    TZ: string;
    DATABASE_URL: string;
    DATABASE_POOL_MIN: number;
    DATABASE_POOL_MAX: number;
    DATABASE_LOG: boolean;
    KAFKA_GROUP_ID: string;
    S3_REGION: string;
    S3_ACCESS_KEY_ID: string;
    S3_SECRET_ACCESS_KEY: string;
    S3_FORCE_PATH_STYLE: boolean;
    JWT_SECRET: string;
    JWT_REFRESH_SECRET: string;
    MFA_SECRET_ENCRYPTION_KEY: string;
    PASSWORD_PEPPER: string;
    JWT_ACCESS_TTL: string;
    JWT_REFRESH_TTL: string;
    ARGON2_MEMORY_COST: number;
    ARGON2_TIME_COST: number;
    ARGON2_PARALLELISM: number;
    EMAIL_SMTP_HOST: string;
    EMAIL_SMTP_PORT: number;
    EMAIL_FROM_ADDRESS: string;
    EMAIL_FROM_NAME: string;
    SKALEAN_AI_BASE_URL: string;
    SKALEAN_AI_API_KEY: string;
    SKALEAN_AI_USE_MOCK: boolean;
    OTEL_DEBUG: boolean;
    OTEL_SERVICE_NAME: string;
    CORS_ORIGINS: string[];
    NEXT_PUBLIC_API_URL: string;
    MCP_SERVER_URL: string;
    SENTRY_DSN?: string | undefined;
    S3_ENDPOINT?: string | undefined;
    S3_KMS_KEY_BASE?: string | undefined;
    EMAIL_SMTP_USER?: string | undefined;
    EMAIL_SMTP_PASSWORD?: string | undefined;
    WHATSAPP_API_URL?: string | undefined;
    WHATSAPP_PHONE_NUMBER_ID?: string | undefined;
    WHATSAPP_ACCESS_TOKEN?: string | undefined;
    OTEL_EXPORTER_OTLP_ENDPOINT?: string | undefined;
    NEXT_PUBLIC_MAPBOX_TOKEN?: string | undefined;
    NEXT_PUBLIC_SENTRY_DSN?: string | undefined;
    CMI_API_URL?: string | undefined;
    CMI_API_KEY?: string | undefined;
    YOUCAN_API_URL?: string | undefined;
    YOUCAN_API_KEY?: string | undefined;
    BARID_ESIGN_API_URL?: string | undefined;
    BARID_ESIGN_API_KEY?: string | undefined;
    ATLAS_VAULT_URL?: string | undefined;
    ATLAS_VAULT_TOKEN?: string | undefined;
}, {
    REDIS_URL: string;
    DATABASE_URL: string;
    S3_ACCESS_KEY_ID: string;
    S3_SECRET_ACCESS_KEY: string;
    JWT_SECRET: string;
    JWT_REFRESH_SECRET: string;
    MFA_SECRET_ENCRYPTION_KEY: string;
    PASSWORD_PEPPER: string;
    APP_VERSION?: string | undefined;
    NODE_ENV?: "development" | "test" | "staging" | "production" | undefined;
    LOG_LEVEL?: "info" | "fatal" | "error" | "warn" | "debug" | "trace" | undefined;
    KAFKA_BROKERS?: unknown;
    KAFKA_CLIENT_ID?: string | undefined;
    SENTRY_DSN?: string | undefined;
    API_PORT?: number | undefined;
    TZ?: string | undefined;
    DATABASE_POOL_MIN?: number | undefined;
    DATABASE_POOL_MAX?: number | undefined;
    DATABASE_LOG?: unknown;
    KAFKA_GROUP_ID?: string | undefined;
    S3_ENDPOINT?: string | undefined;
    S3_REGION?: string | undefined;
    S3_FORCE_PATH_STYLE?: unknown;
    S3_KMS_KEY_BASE?: string | undefined;
    JWT_ACCESS_TTL?: string | undefined;
    JWT_REFRESH_TTL?: string | undefined;
    ARGON2_MEMORY_COST?: number | undefined;
    ARGON2_TIME_COST?: number | undefined;
    ARGON2_PARALLELISM?: number | undefined;
    EMAIL_SMTP_HOST?: string | undefined;
    EMAIL_SMTP_PORT?: number | undefined;
    EMAIL_SMTP_USER?: string | undefined;
    EMAIL_SMTP_PASSWORD?: string | undefined;
    EMAIL_FROM_ADDRESS?: string | undefined;
    EMAIL_FROM_NAME?: string | undefined;
    WHATSAPP_API_URL?: string | undefined;
    WHATSAPP_PHONE_NUMBER_ID?: string | undefined;
    WHATSAPP_ACCESS_TOKEN?: string | undefined;
    SKALEAN_AI_BASE_URL?: string | undefined;
    SKALEAN_AI_API_KEY?: string | undefined;
    SKALEAN_AI_USE_MOCK?: unknown;
    OTEL_EXPORTER_OTLP_ENDPOINT?: string | undefined;
    OTEL_DEBUG?: unknown;
    OTEL_SERVICE_NAME?: string | undefined;
    CORS_ORIGINS?: unknown;
    NEXT_PUBLIC_API_URL?: string | undefined;
    NEXT_PUBLIC_MAPBOX_TOKEN?: string | undefined;
    NEXT_PUBLIC_SENTRY_DSN?: string | undefined;
    MCP_SERVER_URL?: string | undefined;
    CMI_API_URL?: string | undefined;
    CMI_API_KEY?: string | undefined;
    YOUCAN_API_URL?: string | undefined;
    YOUCAN_API_KEY?: string | undefined;
    BARID_ESIGN_API_URL?: string | undefined;
    BARID_ESIGN_API_KEY?: string | undefined;
    ATLAS_VAULT_URL?: string | undefined;
    ATLAS_VAULT_TOKEN?: string | undefined;
}>;
export type Env = z.infer<typeof EnvSchema>;
//# sourceMappingURL=env.schema.d.ts.map